server:
  port: 8500

spring:
  #  enable jpa.show-sql only for debug testing/debugging proposes
  #  jpa:
  #    show-sql: true
  thymeleaf:
    prefix: classpath:/custom-templates/
    cache: false
    mode: HTML
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pgtest
    password: pgtest
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false # disable liquibase to allow manual control

management:
  endpoints:
    web:
      exposure:
        include: '*' # enable all actuator metrics
