scrape_configs:
  - job_name: 'MyDoctorAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8500']
        labels:
          application: 'My Doctor App Spring Boot Application'
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187'] #Need pg-exporter to retrieve metrics for postgres db.
        labels:
          application: 'My Doctor App Database'